FROM docker.io/envoyproxy/envoy:v1.19-latest

LABEL maintainer="Hector Morales <hector.morales.carnice@gmail.com>"
LABEL repo-url="https://github.com/alvidir/tpauth"
LABEL version="alpha"

COPY envoy/envoy.yaml /etc/envoy
CMD ["/usr/local/bin/envoy", "-c", "/etc/envoy/envoy.yaml"]