FROM docker.io/openresty/openresty:alpine

RUN apk update && \
    apk upgrade && \
    apk add curl tar openssl

RUN curl -LO https://github.com/fffonion/lua-resty-openssl/archive/refs/tags/0.8.5.tar.gz && \
    tar -xvzf 0.8.5.tar.gz && \
    mv lua-resty-openssl-0.8.5 /etc/lua-resty-openssl && \
    rm -rf 0.8.5.tar.gz

RUN curl -LO https://github.com/jkeys089/lua-resty-hmac/archive/refs/tags/v0.06.tar.gz && \
    tar -xvzf v0.06.tar.gz && \
    mv lua-resty-hmac-0.06 /etc/lua-resty-hmac && \
    rm -rf v0.06.tar.gz

RUN curl -LO https://github.com/cdbattags/lua-resty-jwt/archive/refs/tags/v0.2.3.tar.gz && \
    tar -xvzf v0.2.3.tar.gz && \
    mv lua-resty-jwt-0.2.3 /etc/lua-resty-jwt && \
    rm -rf v0.2.3.tar.gz

RUN sed -i '1s/^/\
env JWT_HEADER;\n\
env JWT_PUBLIC;\n\
env PROXY_PRIVATE_URI;\n\
env PROXY_PASS_PRIVATE;\n\
env PROXY_PASS_PUBLIC;\n\
env PROXY_REDIRECT;\n\
env REDIS_HOSTNAME;\n/' /usr/local/openresty/nginx/conf/nginx.conf

RUN mkdir /var/log/nginx

RUN apk del curl tar