FROM rust:1.50 as builder

RUN rustup component add rustfmt --toolchain 1.50.0-x86_64-unknown-linux-gnu
WORKDIR /usr/src/tp-auth

COPY *.toml *.lock *.rs ./
COPY proto ./proto
COPY src ./src

RUN cargo install --path .

######## Start a new stage from scratch #######
FROM rust:1.50

RUN rustup component add rustfmt --toolchain 1.50.0-x86_64-unknown-linux-gnu
COPY --from=builder /usr/local/cargo/bin/tp_auth /usr/local/bin/tp_auth

CMD ["tp_auth"]