FROM golang:latest as builder

LABEL maintainer="Hector Morales <hector.morales.carnice@gmail.com>"
LABEL repo-url="https://github.com/alvidir/tp-auth"
LABEL version="alpha"

RUN apt update
RUN apt install -y protobuf-compiler
RUN go get github.com/golang/protobuf/protoc-gen-go

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download
COPY . .

RUN protoc --go_out=plugins=grpc:. --go_opt=paths=source_relative proto/session/*.proto
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o main cmd/tp-auth/main.go

######## Start a new stage from scratch #######
FROM alpine:latest  

RUN apk --no-cache add ca-certificates

WORKDIR /app

COPY --from=builder /app/main .

# Command to run the executable
CMD [ "./main" ]
