CREATE TABLE 'tp-auth'.Profiles (
    ID INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    UserID INTEGER UNSIGNED NOT NULL UNIQUE REFERENCES mastermind.Users,
    ImageUrl VARCHAR(128) DEFAULT 'None' NOT NULL,
    LastConn TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    RegDate TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);