CREATE TYPE IF NOT EXISTS MFA AS ENUM ('app', 'email');

CREATE TABLE IF NOT EXISTS Users (
    id SERIAL PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    email VARCHAR(64) NOT NULL UNIQUE,
    actual_email VARCHAR(64) NOT NULL UNIQUE,
    password VARCHAR(128) NOT NULL,
    multi_factor MFA,
);