FROM docker.io/rust:latest as builder

RUN USER=root cargo new --bin tpauth
RUN apt-get install -y pkg-config libssl-dev libpq-dev

WORKDIR /tpauth
COPY ./Cargo.toml ./Cargo.toml
RUN cargo build --release
RUN rm src/*.rs

RUN rustup component add rustfmt --toolchain 1.53.0-x86_64-unknown-linux-gnu
ADD . ./

RUN rm ./target/release/deps/tpauth*
RUN cargo build --release

######## Start a new stage from scratch #######
FROM docker.io/debian:buster-slim
ARG APP=/usr/src/app

RUN apt-get update \
    && apt-get install -y ca-certificates tzdata pkg-config libssl-dev libpq-dev \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Etc/UTC \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

COPY --from=builder /tpauth/target/release/tpauth ${APP}/tpauth

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./tpauth"]