FROM rust:1.50 as builder

RUN rustup component add rustfmt --toolchain 1.50.0-x86_64-unknown-linux-gnu
WORKDIR /usr/src/oauth

COPY *.toml *.lock *.rs ./
COPY proto ./proto
COPY src ./src

RUN cargo install --path .

######## Start a new stage from scratch #######
FROM rust:1.50

RUN rustup component add rustfmt --toolchain 1.50.0-x86_64-unknown-linux-gnu
COPY --from=builder /usr/local/cargo/bin/oauth /usr/local/bin/oauth

ENV RUST_BACKTRACE=full
CMD ["oauth"]