FROM rust:1.43 as builder

RUN USER=root cargo new --bin oauth
RUN apt-get install pkg-config libssl-dev

WORKDIR /oauth
COPY ./Cargo.toml ./Cargo.toml
RUN cargo build --release
RUN rm src/*.rs

ADD . ./
 
RUN rm ./target/release/deps/rust_docker_web*
RUN cargo build --release

######## Start a new stage from scratch #######
FROM debian:buster-slim
ARG APP=/usr/src/app

RUN apt-get update \
    && apt-get install -y ca-certificates tzdata \
    && rm -rf /var/lib/apt/lists/*

ENV TZ=Etc/UTC \
    APP_USER=appuser

RUN groupadd $APP_USER \
    && useradd -g $APP_USER $APP_USER \
    && mkdir -p ${APP}

COPY --from=builder /oauth/target/release/oauth ${APP}/oauth

RUN chown -R $APP_USER:$APP_USER ${APP}

USER $APP_USER
WORKDIR ${APP}

CMD ["./oauth"]